INSERT INTO GOODLIFE.USERS
(USR_ID, EMAIL, USR_NM, PWD, ROLE_TYP_CD, RGSTRD, INVIT_CD, INVIT_BY, INVIT_DT, USR_STS_ID, FRST_NM, LST_NM, CITY, STATE, ABT_ME)
VALUES(1, 'dhaval.raj@tsgforce.com','dhaval','password','S', 1, 12356, 'Dhaval Raj', CURRENT_DATE, 0, 'Dhaval','Raj','Chicago','IL','I AM DEVELOPER');

INSERT INTO GOODLIFE.USERS
(USR_ID, EMAIL, USR_NM, PWD, ROLE_TYP_CD, RGSTRD, INVIT_CD, INVIT_BY, INVIT_DT, USR_STS_ID, FRST_NM, LST_NM, CITY, STATE, ABT_ME)
VALUES(2,'tom@tsgforce.com','tom','password','I', 1, 100005, 'Dhaval Raj', CURRENT_DATE, 0, 'Tom','Fuentes','Chicago','IL','I AM DEVELOPER');

INSERT INTO GOODLIFE.USERS
(USR_ID, EMAIL, USR_NM, PWD, ROLE_TYP_CD, RGSTRD, INVIT_CD, INVIT_BY, INVIT_DT, USR_STS_ID, FRST_NM, LST_NM, CITY, STATE, ABT_ME)
VALUES(3, 'raj@tsgforce.com','raj','password','S', 1, 12346, 'Dhaval', CURRENT_DATE, 0, 'Dhaval','Raj','Chicago','IL','I AM DEVELOPER');

INSERT INTO GOODLIFE.STUDENT
VALUES(1,1,1,current_time());

INSERT INTO GOODLIFE.STUDENT
(USERID,START_DT)
VALUES(3,current_time());

INSERT INTO GOODLIFE.INSTRUCTOR
VALUES(2,1,1,2,CURRENT_DATE());

INSERT INTO GOODLIFE.CHAPTER
(CHAP_ID,CHAP_TITLE,CHAP_DESCR,ORDER_ID,PUBLISHED)
VALUES(1,'CHAPTER 1 TITLE','CHAPTER 1 DESCRIPTION',1,TRUE);

INSERT INTO GOODLIFE.CHAPTER
(CHAP_ID,CHAP_TITLE,CHAP_DESCR,ORDER_ID,PUBLISHED)
VALUES(2,'CHAPTER 2 TITLE','CHAPTER 2 DESCRIPTION',2,TRUE);

INSERT INTO GOODLIFE.SUBCHAPTER
(SUB_CHAP_ID,CHAPID,SUB_CHAP_DESCR,SUB_CHAP_TITLE,ORDER_ID,PUBLISHED)
VALUES(1,1,'Sub Chapter 1 Description','Sub Chapter 1 Title',1,TRUE);

INSERT INTO GOODLIFE.SUBCHAPTER
(SUB_CHAP_ID,CHAPID,SUB_CHAP_DESCR,SUB_CHAP_TITLE,ORDER_ID,PUBLISHED)
VALUES(2,1,'Sub Chapter 2 Description','Sub Chapter 2 Title',2,TRUE);

INSERT INTO GOODLIFE.SUBCHAPTER
(SUB_CHAP_ID,CHAPID,SUB_CHAP_DESCR,SUB_CHAP_TITLE,ORDER_ID,PUBLISHED)
VALUES(3,1,'Sub Chapter 3 Description','Sub Chapter 3 Title',3,TRUE);

INSERT INTO GOODLIFE.SUBCHAPTER
(SUB_CHAP_ID,CHAPID,SUB_CHAP_DESCR,SUB_CHAP_TITLE,ORDER_ID,PUBLISHED)
VALUES(4,1,'Sub Chapter 4 Description','Sub Chapter 4 Title',4,TRUE);

INSERT INTO GOODLIFE.SUBCHAPTER
(SUB_CHAP_ID,CHAPID,SUB_CHAP_DESCR,SUB_CHAP_TITLE,ORDER_ID,PUBLISHED)
VALUES(5,1,'Sub Chapter 5 Description','Sub Chapter 5 Title',5,TRUE);

INSERT INTO GOODLIFE.USER_STATUS
(USR_STS_ID, USERID, STS_TYP_CD, STRT_DT, END_DT)
VALUES(1,1,'S',CURRENT_DATE()-7,CURRENT_DATE() + 1);

INSERT INTO GOODLIFE.MULTI_CHOICE_Q
(MC_Q_ID,Q_TXT,HELP_TXT,CORR_ANS,SUBCHAPID,ORDER_ID,PUBLISHED)
VALUES(1,'MULTIPLE CHOICE QUESTION 1','THIS IS HELP TEXT',1,1,1,TRUE);

INSERT INTO GOODLIFE.MULTI_CHOICE_Q
(MC_Q_ID,Q_TXT,HELP_TXT,CORR_ANS,SUBCHAPID,ORDER_ID,PUBLISHED)
VALUES(2,'MULTIPLE CHOICE QUESTION 2','THIS IS HELP TEXT',1,1,2,TRUE);

INSERT INTO GOODLIFE.MULTI_CHOICE_Q
(MC_Q_ID,Q_TXT,HELP_TXT,CORR_ANS,SUBCHAPID,ORDER_ID,PUBLISHED)
VALUES(3,'MULTIPLE CHOICE QUESTION 2','THIS IS HELP TEXT',1,2,1,TRUE);

INSERT INTO GOODLIFE.MULTI_CHOICE_OPTION
(OPTION_ID,MULTIQUESID,CHOICE_TXT,PUBLISHED)
VALUES(1,1,'OPTION 1',TRUE);

INSERT INTO GOODLIFE.MULTI_CHOICE_OPTION
(OPTION_ID,MULTIQUESID,CHOICE_TXT,PUBLISHED)
VALUES(2,1,'OPTION 2',TRUE);

INSERT INTO GOODLIFE.MULTI_CHOICE_OPTION
(OPTION_ID,MULTIQUESID,CHOICE_TXT,PUBLISHED)
VALUES(3,2,'OPTION 1',TRUE);

INSERT INTO GOODLIFE.MC_USER_ANS
(USERID,MULTIQUESID,USR_ANS)
VALUES(1,1,1);

INSERT INTO GOODLIFE.MC_USER_ANS
(USERID,MULTIQUESID,USR_ANS)
VALUES(1,2,2);

INSERT INTO GOODLIFE.MC_USER_ANS
(USERID,MULTIQUESID,USR_ANS)
VALUES(1,3,1);

INSERT INTO GOODLIFE.UPLOAD_FILE_Q
(UP_Q_ID,DESCR,SUBCHAPID,HELP_TXT,PUBLISHED)
VALUES(1,'UPLOAD QUESTION 1',3,'UPLOAD QUESTION HELP TEXT',TRUE);

INSERT INTO GOODLIFE.UPLOAD_FILE_Q
(UP_Q_ID,DESCR,SUBCHAPID,HELP_TXT,PUBLISHED)
VALUES(2,'UPLOAD QUESTION 1',4,'UPLOAD QUESTION HELP TEXT',TRUE);

INSERT INTO GOODLIFE.UPLOADED_ANS
(UP_ANS_ID,UPLOADQUESID,MEDIA_TYP_ID,FILE_PATH,USERID,APRVD,SHARED)
VALUES(1,1,1,'C:\FILE',1,TRUE,TRUE);

INSERT INTO GOODLIFE.UPLOADED_ANS
(UP_ANS_ID,UPLOADQUESID,MEDIA_TYP_ID,FILE_PATH,USERID,APRVD,SHARED)
VALUES(2,2,1,'C:\FILE2',1,TRUE,TRUE);

INSERT INTO GOODLIFE.CHAPTER_PAGE
(PAGE_ID,CHAPID,PAGE_NUM,PAGE_URL,PUBLISHED)
VALUES(1,1,1,'HTTP://GOOGLE.COM',TRUE);

INSERT INTO GOODLIFE.CHAPTER_PAGE
(PAGE_ID,CHAPID,PAGE_NUM,PAGE_URL,PUBLISHED)
VALUES(2,1,2,'HTTP://GO.ESPN.COM',TRUE);

INSERT INTO GOODLIFE.CHAPTER_PAGE
(PAGE_ID,CHAPID,PAGE_NUM,PAGE_URL)
VALUES(3,2,1,'HTTP://GOOGLE.COM');

INSERT INTO GOODLIFE.SHORT_ANS_Q
(SA_Q_ID,SUBCHAPID,QUESTION,HELP_TXT,ORDER_ID,PUBLISHED)
VALUES(1,5,'Write about the good life.','No help text required.',1,TRUE);

INSERT INTO GOODLIFE.SHORT_ANS_Q
(SA_Q_ID,SUBCHAPID,QUESTION,HELP_TXT,ORDER_ID,PUBLISHED)
VALUES(2,5,'Write about yourself.','No help text required.',2,TRUE);

INSERT INTO GOODLIFE.SHORT_ANS_USER_ANS
(SAQID,SUBCHAPID,USR_ANS,USERID,APRVD)
VALUES(1,5,'This is my answer.',1,TRUE);

INSERT INTO GOODLIFE.SHORT_ANS_USER_ANS
(SAQID,SUBCHAPID,USR_ANS,USERID,APRVD)
VALUES(2,5,'This is my second answer.',1,TRUE);